"""
GoldBazaar — Excel to JS Data Converter
Runs automatically via GitHub Actions when the Excel file is updated.
DO NOT need to run this manually.
"""
import json, os

try:
    import openpyxl
except ImportError:
    os.system('pip install openpyxl')
    import openpyxl

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
EXCEL_FILE = os.path.join(SCRIPT_DIR, 'gold-loan-providers.xlsx')
JS_FILE    = os.path.join(SCRIPT_DIR, 'gold-loan-providers.js')

wb = openpyxl.load_workbook(EXCEL_FILE)
ws = wb.active

headers = [str(cell.value).strip() if cell.value else '' for cell in ws[1]]
providers = []

for row in ws.iter_rows(min_row=2, values_only=True):
    if not row[0]:
        continue
    r = {headers[i]: (str(v).strip() if v is not None else '') for i, v in enumerate(row)}
    if r.get('active', '').upper() != 'Y':
        continue
    providers.append({
        'name':        r.get('name', ''),
        'logo':        r.get('logo', ''),
        'type':        r.get('type', ''),
        'location':    r.get('location', ''),
        'rate':        r.get('rate', ''),
        'ltv':         r.get('ltv', ''),
        'processing':  r.get('processing', ''),
        'loanMin':     r.get('loan_min', ''),
        'loanMax':     r.get('loan_max', ''),
        'eligibility': r.get('eligibility', ''),
        'documents':   r.get('documents', ''),
        'stars':       int(float(r.get('stars', 4) or 4)),
        'trustBadge':  r.get('trust_badge', ''),
        'website':     r.get('website', ''),
        'scheme1':     r.get('scheme1_name', ''),
        'scheme1Color':r.get('scheme1_color', ''),
        'scheme2':     r.get('scheme2_name', ''),
        'scheme2Color':r.get('scheme2_color', ''),
        'disburse':    r.get('disburse', ''),
        'maxBanner':   r.get('max_loan_banner', ''),
        'featured':    r.get('featured', '').upper() == 'Y',
    })

js = (
    '// Auto-generated from gold-loan-providers.xlsx by GitHub Actions\n'
    '// DO NOT edit this file manually — edit the Excel file instead\n'
    f'var GL_PROVIDERS_DATA = {json.dumps(providers, ensure_ascii=False, indent=2)};\n'
)

with open(JS_FILE, 'w', encoding='utf-8') as f:
    f.write(js)

print(f'OK — {len(providers)} providers written to gold-loan-providers.js')
